// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crvuyaskdjtlrgopuwni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNydnV5YXNrZGp0bHJnb3B1d25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzkzNjcsImV4cCI6MjA3MDAxNTM2N30.MCfs5EeEQALP4-eCUGaAaTuXAx0C-yg8Kknp9PJ68iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});